import { describe, expect, it } from 'vitest';
import {
  readCargoCrateName,
  setCargoLockVersion,
  setCargoManifestVersion,
} from '../src/cargo';

const MANIFEST = `[package]
name = "multi-mind"
version = "1.0.0"
description = "One prompt, many AI chat sites side by side"

[lib]
name = "multi_mind_lib"

[dependencies]
serde = { version = "1", features = ["derive"] }
`;

const LOCK = `# This file is automatically @generated by Cargo.

[[package]]
name = "serde"
version = "1.0.0"

[[package]]
name = "multi-mind"
version = "1.0.0"
dependencies = [
 "serde",
]

[[package]]
name = "tauri"
version = "1.0.0"
`;

describe('readCargoCrateName', () => {
  it('should read the name under [package]', () => {
    expect(readCargoCrateName(MANIFEST)).toBe('multi-mind');
  });

  it('should answer null for a manifest that declares none', () => {
    expect(readCargoCrateName('[package]\nversion = "1.0.0"\n')).toBeNull();
  });
});

describe('setCargoManifestVersion', () => {
  /*
   * The crate's own version is the first in the file. A dependency's inline
   * `version = "1"` sits inside a table further down, and replacing that one
   * would leave the crate unstamped and the dependency pinned to a release.
   */
  it("should set the crate's own version and leave a dependency's alone", () => {
    const stamped = setCargoManifestVersion(MANIFEST, '2.3.4');

    expect(stamped).toContain('name = "multi-mind"\nversion = "2.3.4"');
    expect(stamped).toContain('serde = { version = "1", features = ["derive"] }');
  });

  it('should answer null for a manifest with no version', () => {
    expect(setCargoManifestVersion('[package]\nname = "x"\n', '1.0.0')).toBeNull();
  });

  /*
   * Stamping the version a file already carries has to succeed: a build asked
   * to package what is in the tree packages it rather than stopping.
   */
  it('should be a no-op when the version is already the one asked for', () => {
    expect(setCargoManifestVersion(MANIFEST, '1.0.0')).toBe(MANIFEST);
  });

  it('should leave a CRLF manifest on CRLF', () => {
    const stamped = setCargoManifestVersion(MANIFEST.replaceAll('\n', '\r\n'), '2.3.4');

    expect(stamped).toContain('version = "2.3.4"\r\n');
    expect(stamped).not.toContain('version = "2.3.4"\n\r');
  });
});

describe('setCargoLockVersion', () => {
  it("should set only the named crate's own entry", () => {
    const stamped = setCargoLockVersion(LOCK, 'multi-mind', '2.3.4');

    expect(stamped).toContain('name = "multi-mind"\nversion = "2.3.4"');
    expect(stamped).toContain('name = "serde"\nversion = "1.0.0"');
    expect(stamped).toContain('name = "tauri"\nversion = "1.0.0"');
  });

  it('should answer null for a crate the lock does not list', () => {
    expect(setCargoLockVersion(LOCK, 'absent', '2.3.4')).toBeNull();
  });

  /*
   * The name goes straight into a pattern, so anything that is not a crate
   * name has to be turned away rather than escaped.
   */
  it('should answer null for a name Cargo could not have written', () => {
    expect(setCargoLockVersion(LOCK, 'multi-mind"|.*', '2.3.4')).toBeNull();
  });

  it('should be a no-op when the version is already the one asked for', () => {
    expect(setCargoLockVersion(LOCK, 'multi-mind', '1.0.0')).toBe(LOCK);
  });

  it('should find the entry in a CRLF lock', () => {
    const stamped = setCargoLockVersion(
      LOCK.replaceAll('\n', '\r\n'),
      'multi-mind',
      '2.3.4',
    );

    expect(stamped).toContain('name = "multi-mind"\r\nversion = "2.3.4"');
  });
});
